# Generated by Django 2.0.5 on 2018-05-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='total_time',
            field=models.TimeField(default=0),
        ),
    ]
