# Generated by Django 2.0.5 on 2018-06-07 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='No Header', max_length=25)),
                ('subtitle', models.CharField(default='No Subtitle', max_length=30)),
                ('content', models.CharField(default='No Content', max_length=280)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Member')),
            ],
        ),
    ]
