# Generated by Django 2.0.5 on 2018-05-31 15:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20180531_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_signed_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='sign_in_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 15, 36, 44, 891056, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='sign_out_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 15, 36, 44, 891056, tzinfo=utc)),
        ),
    ]
