# Generated by Django 2.0.5 on 2018-05-31 15:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20180531_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='sign_in_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 15, 46, 19, 730560, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='sign_out_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 15, 46, 19, 730560, tzinfo=utc)),
        ),
    ]
