# Generated by Django 2.0.5 on 2018-05-31 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20180531_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='sign_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='member',
            name='sign_out_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
