# Generated by Django 2.0.5 on 2018-06-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20180531_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_time_block',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
